### ISSUE TITLE
Feature Request: Being able to ALWAYS close the chat. 

### ISSUE THREAD

**Issue by robgev** [iteratehackerspace/gyumri-terminal-chat#9]
When you start writing messages, <q> does not work anymore so you cannot close the program. Think of some workaround.

**Comment by JohnFordBR** [comment]
press q

**Comment by JohnFordBR** [comment]
or esc

**Comment by JohnFordBR** [comment]
two  times

**Comment by robgev** [comment]
okay this one can be clossed. Should do esc and then esc/q
